name: Install HRMS 
on:
  workflow_dispatch:
    inputs:
      product:
        required: true
        description: Product
        default: pdt  
jobs:
  deploy:
    name: Configure hrms instance
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::734522607489:role/github-action
        aws-region: ap-south-1
    - name: Configure Instance
      run: |
        export pubIP=$(aws ec2 describe-instances   --filters "Name=tag:Name,Values=test-company-hrms-ec2"   --query "Reservations[*].Instances[*].PublicDnsName"   --output text)
        echo "Public IP="$pubIP
        echo "${{ secrets.SSH_KEY }}" > "${{ github.workspace }}/scripts/id_rsa"
        chmod 600 "${{ github.workspace }}/scripts/id_rsa"

        # Replace YOUR_EC2_PUBLIC_IP with the actual public IP of your EC2 instance
        EC2_PUBLIC_IP="$pubIP"
        # Replace PRIVATE_KEY_PATH with the path to your private key file
        PRIVATE_KEY_PATH="${{ github.workspace }}/scripts/id_rsa"
        # Replace SCRIPT_PATH with the path to your script on the local machine
        SCRIPT_PATH="${{ github.workspace }}/scripts/hrms_install.sh"
        # Copy the script to the EC2 instance
        scp -i $PRIVATE_KEY_PATH $SCRIPT_PATH ubuntu@$EC2_PUBLIC_IP:/tmp/
        # Connect to the EC2 instance and execute the script
        ssh -i $PRIVATE_KEY_PATH ec2-user@$EC2_PUBLIC_IP "bash /tmp/$(basename $SCRIPT_PATH) /tmp/$pubIP"        